"""shell_completion — emit shell completion scripts for the `yaah` CLI.

Used by: the `yaah completion <shell>` subcommand. The user pipes the output
into their shell config (`yaah completion bash >> ~/.bash_completion`, or
similar for zsh).
Where: leaf module. PURE — no I/O, no state; the CLI just prints whatever
this returns.
Why: tab-completion is the first thing power-users miss between `pip install`
and a productive workflow. Without it, `yaah <TAB>` does nothing useful and
typos like `yaah resmue` surface only on run.

The completion scripts are HARDCODED (one constant string per shell), not
generated by introspecting the CLI parser. The hand-rolled approach beats
introspection here because: (a) the parser is small and changes rarely,
(b) introspection adds machinery to a CLI that the engine refuses to bring,
(c) the resulting scripts need shell-specific idioms (compgen for bash,
_arguments for zsh) that don't translate cleanly from one model.

Targets Python 3.9+.
"""
from __future__ import annotations

# The verbs the user can pick first. Mirrors _SUBCOMMANDS in cli.py — keep in
# sync (a divergence shows up as a verb the user can run but not tab-complete,
# or vice versa). Tested in test_completion.py.
_VERBS = ("init", "scaffold", "run", "list", "resume", "clear",
          "validate", "explain", "trace", "baton-schema", "doctor",
          "manual", "mcp-serve",
          "completion")

# Per-verb flag sets used in completion. These are what the user can usefully
# tab through; not exhaustive (--debug works on most verbs and is offered
# everywhere via the global block).
_TRACE_FLAGS = ("--pretty", "--errors-only", "--cost", "--last")
_PIPELINE_FLAGS = ("--fake", "--debug")
_LIST_FLAGS = ("--json",)
_GLOBAL_FLAGS = ("--help", "-h", "--version", "-V", "--debug")
_ARCHETYPES = ("linear", "branch-with-gate", "fork-fanin")
_SHELLS = ("bash", "zsh")


_BASH_TEMPLATE = """\
# yaah bash completion — generated by `yaah completion bash`.
# Install:  yaah completion bash > ~/.local/share/bash-completion/completions/yaah
# Or source in .bashrc:  source <(yaah completion bash)

_yaah_completion() {{
  local cur prev words cword
  COMPREPLY=()
  cur="${{COMP_WORDS[COMP_CWORD]}}"
  cword=${{COMP_CWORD}}

  if [ "$cword" -eq 1 ]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "{global_flags}" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "{verbs}" -- "$cur") )
    fi
    return 0
  fi

  local subcmd="${{COMP_WORDS[1]}}"
  case "$subcmd" in
    trace)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "{trace_flags} --debug" -- "$cur") )
      else
        COMPREPLY=( $(compgen -f -X '!*.jsonl' -- "$cur") )
      fi
      ;;
    scaffold)
      if [ "$cword" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "{archetypes}" -- "$cur") )
      fi
      ;;
    init)
      COMPREPLY=( $(compgen -d -- "$cur") )
      ;;
    completion)
      COMPREPLY=( $(compgen -W "{shells}" -- "$cur") )
      ;;
    doctor)
      ;;  # no further completion
    list)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "{list_flags} --debug" -- "$cur") )
      else
        COMPREPLY=( $(compgen -f -X '!*.json' -- "$cur") )
      fi
      ;;
    *)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "{pipeline_flags}" -- "$cur") )
      else
        COMPREPLY=( $(compgen -f -X '!*.json' -- "$cur") )
      fi
      ;;
  esac
}}

complete -F _yaah_completion yaah
"""


_ZSH_TEMPLATE = """\
#compdef yaah
# yaah zsh completion — generated by `yaah completion zsh`.
# Install:  yaah completion zsh > "${{fpath[1]}}/_yaah"  # then restart zsh
# Or source in .zshrc:  source <(yaah completion zsh)

_yaah() {{
  local -a commands
  commands=(
    'init:scaffold a linear starter pipeline'
    'scaffold:scaffold from a named archetype'
    'run:run the configured pipeline'
    'list:show parked gates (the mailbox view)'
    'resume:deliver a decision to a parked gate'
    'clear:graceful reset of the harness'
    'validate:validate root + pipeline; no run'
    'explain:print the effective config'
    'trace:summarize a run trace'
    'baton-schema:JSON Schema of decision.json for a parked baton'
    'doctor:diagnose install'
    'manual:print the generated agent manual'
    'mcp-serve:serve validate/run/gates as MCP tools over stdio'
    'completion:emit shell completion script'
  )

  if (( CURRENT == 2 )); then
    _describe -t commands 'yaah commands' commands
    return
  fi

  case "$words[2]" in
    trace)
      _arguments \\
        '--pretty[per-run tree of stages/calls/errors]' \\
        '--errors-only[CI-shaped check; exits non-zero on errors]' \\
        '--cost[compact per-model cost rollup]' \\
        '--last[filter to most recent N runs]:N:' \\
        '--debug[full traceback on errors]' \\
        '*:trace.jsonl:_files -g "*.jsonl"'
      ;;
    scaffold)
      if (( CURRENT == 3 )); then
        _values 'archetype' {archetypes_zsh}
      else
        _files -/
      fi
      ;;
    init)
      _files -/
      ;;
    completion)
      _values 'shell' bash zsh
      ;;
    list)
      _arguments \\
        '--json[parseable shape]' \\
        '--debug[full traceback]' \\
        '*:root.json:_files -g "*.json"'
      ;;
    doctor) ;;
    *)
      _arguments \\
        '--fake[merge _fake overlay]' \\
        '--debug[full traceback]' \\
        '*:root.json:_files -g "*.json"'
      ;;
  esac
}}

_yaah "$@"
"""


def bash_completion() -> str:
    """Bash completion script. Hand-rolled compgen; tested against the verb
    list to catch drift from cli._SUBCOMMANDS."""
    return _BASH_TEMPLATE.format(
        verbs=" ".join(_VERBS),
        global_flags=" ".join(_GLOBAL_FLAGS),
        trace_flags=" ".join(_TRACE_FLAGS),
        list_flags=" ".join(_LIST_FLAGS),
        pipeline_flags=" ".join(_PIPELINE_FLAGS),
        archetypes=" ".join(_ARCHETYPES),
        shells=" ".join(_SHELLS),
    )


def zsh_completion() -> str:
    """Zsh completion script. Uses _arguments + _values — the idiomatic zsh
    completion shape (the bash-style compgen approach works in zsh's
    bashcompinit but reads as foreign)."""
    return _ZSH_TEMPLATE.format(archetypes_zsh=" ".join(_ARCHETYPES))


def render(shell: str) -> str:
    """Dispatch by shell name. Unknown shell -> ValueError naming the
    supported set (CLI surfaces this as exit 2 + message)."""
    if shell == "bash":
        return bash_completion()
    if shell == "zsh":
        return zsh_completion()
    raise ValueError("unknown shell {!r}; supported: {}".format(
        shell, ", ".join(_SHELLS)))
