"""LangfuseTraceSink — forward trace records to Langfuse (R5a).

Used by: the runtime when `trace.sink: {type: langfuse, ...}`; subscribed to the
`trace` topic. The write-side twin of LangfusePromptSource — we already READ
prompts from Langfuse; this WRITES traces back.
Where: a swap-in TraceSink adapter (binds to Langfuse).
Why: Langfuse's UI gives the dashboard + cost aggregation + evals for free, so
sending spans there REDUCES how much custom observability we build. Langfuse
also does the token->$ math, so the Langfuse path needs no local price-map.

Span -> Langfuse mapping: `corr`->trace, `model_call`->generation (model +
tokens, so Langfuse computes cost), every other span->observation span. The
client is injected for testability (a stub in tests); the real Langfuse client is
built lazily, only when used.

SDK churn: the Langfuse client API changed shape across majors — v2 exposed
manual `.trace()/.generation()/.span()`; v4 is OpenTelemetry-based and exposes
`.start_observation(as_type=...)`. We detect which is present and map onto it, so
`pip install yaah-harness[langfuse]` works on either. The v4 path attaches every
observation to the trace by `trace_id` (our `corr`, a 32-hex id OTel accepts); it
does NOT reconstruct parent/child nesting (OTel span ids are generated by the SDK,
not us) — observations land flat under the run. The native long-term path is an
OTLP sink (see ROADMAP); this keeps the bespoke-client integration honest until
then. The two majors also differ on USAGE: v4 takes an open `usage_details` map
that carries the prompt-cache classes under their own keys, v2 a typed model
with only input/output — so the v2 path folds cache into `input` (see
`_usage_v2`) rather than posting keys that model has no field for.

v1 approximations (refine against a live instance): spans carry monotonic
durations, not wall-clock timestamps, so duration rides in metadata and Langfuse
timestamps on ingestion. Cosmetic — trace/generation/cost land correctly.

Targets Python 3.9+.
"""
from __future__ import annotations

import re
from typing import Any, Dict, Optional, Set

from ...agents.api_provider import USAGE_TOKEN_KEYS
from ...core import Envelope
from ...trace import TraceSink

_OTEL_TRACE_ID = re.compile(r"\A[0-9a-f]{32}\Z")

# yaah's provider-agnostic token key -> Langfuse's v4 usage_details key. Keyed on
# api_provider.Usage's names and required to COVER api_provider.USAGE_TOKEN_KEYS
# (scenario_usage_vocabulary_is_shared pins that); both builders below ITERATE
# this vocabulary rather than naming classes inline, so a token class added to
# Usage either flows through or fails loudly — never gets silently dropped from
# every generation, which is the silent-$0 drift the Usage type exists to stop.
_V4_USAGE_KEYS = {"tokens_in": "input", "tokens_out": "output",
                  "tokens_cache_read": "cache_read_input_tokens",
                  "tokens_cache_write": "cache_creation_input_tokens"}

#: The one OUTPUT class; every other token class is an input class (that is the
#: only structural distinction either SDK's usage shape makes).
_OUTPUT_KEY = "tokens_out"
_INPUT_TOKEN_KEYS = tuple(k for k in USAGE_TOKEN_KEYS if k != _OUTPUT_KEY)
#: Written even as a zero — a generation with no `input`/`output` reads as
#: missing data in Langfuse, whereas an absent cache class just means no caching.
_V4_ALWAYS = ("tokens_in", _OUTPUT_KEY)


def _trace_context(corr: str) -> Optional[Dict[str, str]]:
    """A v4 trace_context if `corr` is a valid (32-hex, non-zero) OTel trace id,
    else None — let the SDK mint its own id rather than be rejected."""
    if _OTEL_TRACE_ID.match(corr) and corr != "0" * 32:
        return {"trace_id": corr}
    return None


def _usage_details_v4(r: Dict[str, Any]) -> Dict[str, int]:
    """v4 `usage_details` for one model_call record: every token class in the
    shared vocabulary, renamed to Langfuse's own dialect. Always `input`/`output`
    (see _V4_ALWAYS); any other class only when non-zero, so a non-caching
    generation keeps the two-key shape Langfuse has always seen.

    Langfuse computes cost itself, and without the split it would price the cache
    classes at the full input rate (the same over-report the file-path aggregator
    was fixed for; see yaah.trace.aggregate for the rates). v4's usage_details is
    an OPEN key->count map, so extra dialect keys are carried, not rejected."""
    usage: Dict[str, int] = {}
    for src in USAGE_TOKEN_KEYS:
        n = r.get(src, 0) or 0
        if n or src in _V4_ALWAYS:
            usage[_V4_USAGE_KEYS[src]] = n
    return usage


def _usage_v2(r: Dict[str, Any]) -> Dict[str, int]:
    """v2 `usage` for one model_call record — the legacy manual client's TYPED
    usage model, whose fields are input/output/total (+unit/cost) and nothing
    else. So EVERY input class (_INPUT_TOKEN_KEYS, i.e. the vocabulary minus the
    one output class) is FOLDED INTO `input` rather than sent under anthropic key
    names the model would reject — a class added to Usage joins the sum instead
    of vanishing.

    The fold is lossy in one direction, deliberately: on v2 a cache read is
    billed at the full input rate, so a cache-heavy run reads HIGH — an upper
    bound, the same convention pre-split traces get. Dropping the cached tokens
    instead would read LOW, which is the failure that actually misleads. v4 is
    the accurate path; this keeps the legacy SDK honest and, unlike sending
    unknown keys into a typed model, is verifiable offline."""
    return {"input": sum(r.get(k, 0) or 0 for k in _INPUT_TOKEN_KEYS),
            "output": r.get(_OUTPUT_KEY, 0) or 0}


class LangfuseTraceSink(TraceSink):
    def __init__(self, *, client: Any = None, **client_opts: Any) -> None:
        # `client` is the external dependency, injected for testability: any object
        # exposing the v2 (.trace/.generation/.span) or v4 (.start_observation)
        # surface. Defaults to a lazily-built real Langfuse client. Tests pass a
        # stub so this runs without the SDK / creds.
        self._client_opts = client_opts
        self._client: Any = client
        self._seen_traces: Set[str] = set()  # v2 only: corr we've opened a trace for

    def _client_(self) -> Any:
        if self._client is None:  # pragma: no cover - real SDK shim (lazy, integration-only)
            from langfuse import Langfuse

            self._client = Langfuse(**self._client_opts)
        return self._client

    async def handle(self, env: Envelope) -> None:
        r = env.payload
        corr = r.get("corr")
        if not corr:
            return
        client = self._client_()
        name = r.get("name")
        obs_name = r.get("stage") or r.get("tool") or name
        metadata = {k: r[k] for k in ("stage", "status", "duration_ms", "tool") if k in r}

        if hasattr(client, "start_observation"):       # v4 (OpenTelemetry)
            self._emit_v4(client, r, name, obs_name, metadata, corr)
        else:                                           # v2 (manual client)
            self._emit_v2(client, r, name, obs_name, metadata, corr)

    def _emit_v4(self, client: Any, r: Dict[str, Any], name: Any, obs_name: Any,
                 metadata: Dict[str, Any], corr: str) -> None:
        tctx = _trace_context(corr)
        common: Dict[str, Any] = dict(name=obs_name, metadata=metadata)
        if tctx is not None:
            common["trace_context"] = tctx
        if name == "model_call":
            obs = client.start_observation(
                as_type="generation", model=r.get("model"),
                usage_details=_usage_details_v4(r),
                **common)
        else:
            obs = client.start_observation(as_type="span", **common)
        obs.end()

    def _emit_v2(self, client: Any, r: Dict[str, Any], name: Any, obs_name: Any,
                 metadata: Dict[str, Any], corr: str) -> None:
        if corr not in self._seen_traces:
            client.trace(id=corr, name="run")
            self._seen_traces.add(corr)
        common: Dict[str, Any] = dict(
            trace_id=corr, id=r.get("id"), parent_observation_id=r.get("parent"),
            name=obs_name, metadata=metadata)
        if name == "model_call":
            client.generation(
                model=r.get("model"), usage=_usage_v2(r), **common)
        else:
            client.span(**common)
