"""LangfuseTraceSink — forward trace records to Langfuse (R5a).

Used by: the runtime when `trace.sink: {type: langfuse, ...}`; subscribed to the
`trace` topic. The write-side twin of LangfusePromptSource — we already READ
prompts from Langfuse; this WRITES traces back.
Where: a swap-in TraceSink adapter (binds to Langfuse).
Why: Langfuse's UI gives the dashboard + cost aggregation + evals for free, so
sending spans there REDUCES how much custom observability we build. Langfuse
also does the token->$ math, so the Langfuse path needs no local price-map.

Span -> Langfuse mapping: `corr`->trace, `model_call`->generation (model +
tokens, so Langfuse computes cost), every other span->observation span. The
client is injected for testability (a stub in tests); the real Langfuse client is
built lazily, only when used.

SDK churn: the Langfuse client API changed shape across majors — v2 exposed
manual `.trace()/.generation()/.span()`; v4 is OpenTelemetry-based and exposes
`.start_observation(as_type=...)`. We detect which is present and map onto it, so
`pip install yaah-harness[langfuse]` works on either. The v4 path attaches every
observation to the trace by `trace_id` (our `corr`, a 32-hex id OTel accepts); it
does NOT reconstruct parent/child nesting (OTel span ids are generated by the SDK,
not us) — observations land flat under the run. The native long-term path is an
OTLP sink (see ROADMAP); this keeps the bespoke-client integration honest until
then.

v1 approximations (refine against a live instance): spans carry monotonic
durations, not wall-clock timestamps, so duration rides in metadata and Langfuse
timestamps on ingestion. Cosmetic — trace/generation/cost land correctly.

Targets Python 3.9+.
"""
from __future__ import annotations

import re
from typing import Any, Dict, Optional, Set

from ...core import Envelope
from ...trace import TraceSink

_OTEL_TRACE_ID = re.compile(r"\A[0-9a-f]{32}\Z")


def _trace_context(corr: str) -> Optional[Dict[str, str]]:
    """A v4 trace_context if `corr` is a valid (32-hex, non-zero) OTel trace id,
    else None — let the SDK mint its own id rather than be rejected."""
    if _OTEL_TRACE_ID.match(corr) and corr != "0" * 32:
        return {"trace_id": corr}
    return None


class LangfuseTraceSink(TraceSink):
    def __init__(self, *, client: Any = None, **client_opts: Any) -> None:
        # `client` is the external dependency, injected for testability: any object
        # exposing the v2 (.trace/.generation/.span) or v4 (.start_observation)
        # surface. Defaults to a lazily-built real Langfuse client. Tests pass a
        # stub so this runs without the SDK / creds.
        self._client_opts = client_opts
        self._client: Any = client
        self._seen_traces: Set[str] = set()  # v2 only: corr we've opened a trace for

    def _client_(self) -> Any:
        if self._client is None:  # pragma: no cover - real SDK shim (lazy, integration-only)
            from langfuse import Langfuse

            self._client = Langfuse(**self._client_opts)
        return self._client

    async def handle(self, env: Envelope) -> None:
        r = env.payload
        corr = r.get("corr")
        if not corr:
            return
        client = self._client_()
        name = r.get("name")
        obs_name = r.get("stage") or r.get("tool") or name
        metadata = {k: r[k] for k in ("stage", "status", "duration_ms", "tool") if k in r}

        if hasattr(client, "start_observation"):       # v4 (OpenTelemetry)
            self._emit_v4(client, r, name, obs_name, metadata, corr)
        else:                                           # v2 (manual client)
            self._emit_v2(client, r, name, obs_name, metadata, corr)

    def _emit_v4(self, client: Any, r: Dict[str, Any], name: Any, obs_name: Any,
                 metadata: Dict[str, Any], corr: str) -> None:
        tctx = _trace_context(corr)
        common: Dict[str, Any] = dict(name=obs_name, metadata=metadata)
        if tctx is not None:
            common["trace_context"] = tctx
        if name == "model_call":
            obs = client.start_observation(
                as_type="generation", model=r.get("model"),
                usage_details={"input": r.get("tokens_in", 0),
                               "output": r.get("tokens_out", 0)},
                **common)
        else:
            obs = client.start_observation(as_type="span", **common)
        obs.end()

    def _emit_v2(self, client: Any, r: Dict[str, Any], name: Any, obs_name: Any,
                 metadata: Dict[str, Any], corr: str) -> None:
        if corr not in self._seen_traces:
            client.trace(id=corr, name="run")
            self._seen_traces.add(corr)
        common: Dict[str, Any] = dict(
            trace_id=corr, id=r.get("id"), parent_observation_id=r.get("parent"),
            name=obs_name, metadata=metadata)
        if name == "model_call":
            client.generation(
                model=r.get("model"),
                usage={"input": r.get("tokens_in", 0), "output": r.get("tokens_out", 0)},
                **common)
        else:
            client.span(**common)
